### ISSUE TITLE
Any in src/test/proto cause all protos defined in /src/main/proto to be generated in generated-test-sources 

### ISSUE THREAD

**Issue by ericzundel** [sergei-ivanov/maven-protoc-plugin#22] opened 2014-12-02 17:19 UTC
To replicate this issue, create a project with a .proto file in it:
```
src/main/proto/foo.proto
```

Run `mvn compile` and the generated java files go in `targets/generated-sources`.  So far so good.

Now, rm -rf the target directory and put any file into the src/test/proto directory:

```
rm -rf target
touch src/test/proto/README.md
```

Re-run `mvn compile`.  The proto files are now all generated into `targets/generated-test-sources` and invisible outside of scope "test" to other projects.

The issue is that there is only one java output directory and if you set it twice using Protoc.setJavaOutputDirectory(), the last one wins.  We could patch around this issue by skipping the setJavaOutputDirectory() in  if there are no valid .proto source files inside of ProtocTestCompileMojo.addProtocBuilderParameters().  That will fix this case, but might allow you to define protos both in src/main/proto and src/test/proto in the same project.

**Comment by sergei-ivanov** [comment] 2015-02-02 13:34
Hello Eric,

I finally got some time to take a look at the issue. I could reproduce the problem with the sample project you've provided: as soon as I added proto definitions under ```src/test/proto```, all protos were generated into ```generated-test-sources```.

The problem was again with the POM configuration. Two problems as a matter of fact. Firstly, your executions inside profiles did not have unique ids. As a result, test profile execution overrode the default execution from the main profile. Secondly, with the profiles in place, you do not need to have a plugin declaration with executions inside the ```build``` element. You need to drop the executions and move the plugin declaration into ```pluginManagement``` section. Executions will be automatically invoked by the respective profiles.

Please take a look at the following gist with an updated POM:
https://gist.github.com/sergei-ivanov/c56c0806ed36ec2ad709

A quick summary of changes:
1. I had to drop the repo config because we use repo manager that is configured in ```settings.xml```. Please disregard this change.
2. I had to add a unique execution id to each of the plugin executions inside profiles.
3. I dropped the extraneous executions from the ```build``` section and moved the plugin declaration into ```pluginManagement```

Regarding the problem with IntelliJ IDEA. I do remember it had an issue with nested directories inside ```generated-sources``` and ```generated-test-sources```, but those problems have been resolved by JetBrains team long time ago. Should not be an issue at present, and certainly not a problem here.

I hope the above helps.

Kind regards,
Sergei

**Comment by sergei-ivanov** [comment] 2015-02-28 02:39
Eric,

I am closing the issue, please reopen if you have got any further questions.

Kind regards,
Sergei

**Closed by sergei-ivanov** 2015-02-28 02:39 UTC

**Comment by ericzundel** [comment] 2015-02-28 03:10
Thanks Sergei
